version: "3.9"

services:
  # web:
  #   depends_on:
  #     - postgres_db 
  #   build:
  #     context: ./web
  #     dockerfile: Dockerfile
  #   image: django-k8s:v1
  #   environment:
  #     - PORT=8020
  #   env_file:
  #     - web/.env
  #   ports:
  #     - "8001:8020"
  #   command: sh -c "chmod +x /app/migrate.sh && sh /app/migrate.sh && /app/entrypoint.sh"
  postgres_db:
    image: postgres
    restart: always
    command: -p 5434
    env_file:
      - web/.env
    expose:
      - 5434
    ports:
      - "5434:5434"
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data:
